### ISSUE TITLE
Hello Mrs for loop!

### ISSUE THREAD

**Issue by hdrdavies** [fcscripters/tuber#33]
https://github.com/fcscripters/tuber/blob/master/handlers/journeyApi.js#L81

**Comment by hdrdavies** [comment]
Also - quite a lot of whitespace, comments and console logs in that file

**Comment by sohilpandya** [comment]
for each is ok.

**Comment by hdrdavies** [comment]
apologies I meant this for loop

https://github.com/fcscripters/tuber/blob/master/handlers/journeyApi.js#L86

**Comment by sohilpandya** [comment]
@hdrdavies can we close this?

**Comment by hdrdavies** [comment]
nice! @sohilpandya how did you solve not using a for loop?

**Comment by sohilpandya** [comment]
I think Gethin got pissed off and solved it himself! lol.

**Comment by hdrdavies** [comment]
hahaha.

@thegsi ?
