### ISSUE TITLE
arrival & departure autocomplete files are empty?

### ISSUE THREAD

**Issue by hdrdavies** [fcscripters/tuber#35]
Are they a work in progress or...?

**Comment by Conorc1000** [comment]
work in progress, please be patient with us in these turbulent times. we thank you for your custom.

**Comment by sohilpandya** [comment]
Will close this once autocomplete works

**Comment by sohilpandya** [comment]
@hdrdavies can we close this? we have implemented autocomplete. :smile:

**Comment by hdrdavies** [comment]
nice work!
